### ISSUE TITLE
gulp release out of memory

### ISSUE THREAD

**Issue by RussellGrew** [TerriaJS/TerriaMap#374]
@soyarsauce suggested I make an issue for this. 

To be clear it isn't a roadblock.

From a clean TerriaMap pull

```
[08:12:55] Starting 'release'...
[08:12:55] Starting 'render-datasource-templates'...
[08:12:55] Finished 'render-datasource-templates' after 8.11 ms
[08:12:55] Starting 'copy-terriajs-assets'...
[08:12:57] Finished 'copy-terriajs-assets' after 1.91 s
[08:12:57] Starting 'release-app'...
[08:12:57] Starting 'check-terriajs-dependencies'...
[08:12:57] Finished 'check-terriajs-dependencies' after 1.47 ms
[08:12:57] Starting 'write-version'...
[08:12:57] Finished 'write-version' after 67 ms
[08:12:57] Starting 'releaseApp'...
(node:6100) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6654F121A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF6654CA5B6 node::MakeCallback+4518
 3: 00007FF6654CAFA0 node_module_register+2160
 4: 00007FF66575B3EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF66575B31F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF665C99304 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF665C8FA67 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF665C8DFDC v8::internal::ScavengeJob::operator=+18748
 9: 00007FF665C96F57 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF665C96FD6 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF665839DD7 v8::internal::Factory::NewFillerObject+55
12: 00007FF6658D1ABA v8::internal::WasmJs::Install+29530
13: 0000017C568DC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! terriajs-map@0.0.1 gulp: `gulp "release"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the terriajs-map@0.0.1 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
and when I `npm run gulp release` again it builds.

This is on a VM with 8 GB RAM and Xeon Gold 6130 CPU running Windows Server 2016 and node v10.15.0.

And the debug log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp',
1 verbose cli   'release' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info lifecycle terriajs-map@0.0.1~pregulp: terriajs-map@0.0.1
6 info lifecycle terriajs-map@0.0.1~gulp: terriajs-map@0.0.1
7 verbose lifecycle terriajs-map@0.0.1~gulp: unsafe-perm in lifecycle true
8 verbose lifecycle terriajs-map@0.0.1~gulp: PATH: *removed for github post brevity*
9 verbose lifecycle terriajs-map@0.0.1~gulp: CWD: D:\russell\TerriaMap
10 silly lifecycle terriajs-map@0.0.1~gulp: Args: [ '/d /s /c', 'gulp "release"' ]
11 silly lifecycle terriajs-map@0.0.1~gulp: Returned: code: 134  signal: null
12 info lifecycle terriajs-map@0.0.1~gulp: Failed to exec gulp script
13 verbose stack Error: terriajs-map@0.0.1 gulp: `gulp "release"`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid terriajs-map@0.0.1
15 verbose cwd D:\russell\TerriaMap
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp" "release"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 134
22 error terriajs-map@0.0.1 gulp: `gulp "release"`
22 error Exit status 134
23 error Failed at the terriajs-map@0.0.1 gulp script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by steve9164** [comment]
I just found this while closing up old issues. For the sake of others that might find this:

To avoid these errors when building TerriaMap please set a higher Node.js allocation limit. E.g.
```bash
export NODE_OPTIONS=--max_old_space_size=4096
npm run gulp release
```

Experiment with higher values than 4096 if `Allocation failed - JavaScript heap out of memory` still occurs.
