### ISSUE TITLE
Inpm nstallation Error Ubuntu

### ISSUE THREAD

**Issue by KoalaGeo** [TerriaJS/TerriaMap#408]
Hi, 

Following the getting started documentation on Ubuntu 18.04 I'm getting an error at the npm install stage, as below.
 
```
terria@terria:~/TerriaMap$ npm install
loadDep:yargs → resolveWi ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine proj4js-defs@0.0.1: wanted: {"node":">=0.6.x","npm":"1.1.x"} (currenpm WARN deprecated proj4js@0.3.0: please use 'proj4' instead, proj4js is not maintained
npm ERR! Linux 5.0.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/terria/TerriaMap/npm-debug.log

terria@terria:~/TerriaMap$ npm run gulp

> terriajs-map@0.0.1 gulp /home/terria/TerriaMap
> gulp

sh: 1: gulp: not found

npm ERR! Linux 5.0.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "gulp"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! terriajs-map@0.0.1 gulp: `gulp`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the terriajs-map@0.0.1 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the terriajs-map package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs terriajs-map
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls terriajs-map
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/terria/TerriaMap/npm-debug.log
```

**Comment by kring** [comment]
The only thing that jumps out at me is that your npm version is very old. Typically node 8.10.0 would use npm v5.6.0 (according to https://nodejs.org/en/download/releases/). Can you try upgrading your npm version? Upgrading to node 10 is a good idea, too, if you can.

**Comment by KoalaGeo** [comment]
That's done it, thank you!
