### ISSUE TITLE
run "npm run gulp  watch" fail, but  "npm run gulp" is ok

### ISSUE THREAD

**Issue by MockerPeking** [TerriaJS/TerriaMap#441]
with  Ubuntu 16.04 node 6  ,error message shows below, if use "sudo" prifix, it will  be stucked  without any error message. 
[16:02:13] 'waitForTerriaJsAssetChanges' errored after 3.09 ms
[16:02:13] Error: watch /home/erick/WebstormProjects/TerriaMap/node_modules/terriajs/wwwroot ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/erick/WebstormProjects/TerriaMap/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/erick/WebstormProjects/TerriaMap/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/erick/WebstormProjects/TerriaMap/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/erick/WebstormProjects/TerriaMap/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/erick/WebstormProjects/TerriaMap/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/erick/WebstormProjects/TerriaMap/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
[16:02:13] 'watch-terriajs-assets' errored after 27 s
[16:02:13] 'watch' errored after 27 s
[16:02:13] The following tasks did not complete: watch-datasource-templates, watch-app, watchDatasourceTemplates, watchApp
[16:02:13] Did you forget to signal async completion?

**Comment by steve9164** [comment]
Hi @MockerPeking. A quick search of the "ENOSPC" error says that it signals no space left on device. Is it possible that your system/virtual machine that you're building Terria on ran out of storage space? Off the top of my head I'd estimate that `gulp watch` could take maybe 100MB extra storage space to allow incremental builds to happen rather than compiling everything in memory, but I haven't measured it. How much free space do you have?

**Comment by MockerPeking** [comment]
Thanks for the reply,！actually, the above error message was obtained after I tested multiple projects on ubuntu16.04 & webstorm, it should be due to the memory usage close to the set 8g memory limit, but webstorm did not report an error
