### ISSUE TITLE
Problem running TerriaMap on Linux

### ISSUE THREAD

**Issue by davidedelerma** [TerriaJS/TerriaMap#452]
Trying to run TerriaMap locally on WSL but get the following eror:
```> terriajs-cesium@1.68.0 postinstall /c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/terriajs-cesium
> bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"


> terriajs@7.11.4 postinstall /c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/terriajs
> gulp post-npm-install

[14:12:20] Using gulpfile /c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/terriajs/gulpfile.js
[14:12:20] Starting 'post-npm-install'...
[14:12:20] Starting 'copy-cesium-assets'...
[14:12:20] 'copy-cesium-assets' errored after 3.31 ms
[14:12:20] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/terriajs-cesium/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at /c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/terriajs/gulpfile.js:78:33
    at copy-cesium-assets (/c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:429:14)
    at runBound (domain.js:442:12)
    at asyncRunner (/c/Users/Davide.DeLerma/projects/catapult_repos/terria/TerriaMap/node_modules/async-done/index.js:55:18)
[14:12:20] 'post-npm-install' errored after 11 ms
npm WARN react-datepicker@0.53.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@0.53.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terriajs@7.11.4 postinstall: `gulp post-npm-install`
```
installation following the doc works  for some previous commit, I tried with commit: `8065aca3504014e3d14972ad9118872caaeb83e7`
In the latter case, the token to retrieve the base map in Cesium seems wrong so I don't see any basemap, but inserting the right token finally I can see the base map.

Node version: 14.2.0
NPM version: 6.14.4

**Comment by donnitazen** [comment]
Hi Davide, what do you mean by "putting the right token"? 

I did have this issue and needed to downgrade nodejs from version 14. The error is gone, but I still see empty basemap.

Maybe I should also do something with the token.

**Comment by davidedelerma** [comment]
Basically to see the basemap you need a ssecurity token to be set. I had it working reverting to previous commit and using the token from latest commit of master. The access token need to be set in: `<your-local-path>/node_modules/terriajs-cesium/Build/CesiumUnminified/Cesium.js` and `<your -local-path>/node_modules/terriajs-cesium/Source/Core/Ion.js` . It is still weird that older commits work fine wqith node 14 but not the latest, maybe something has goone wrong during latest commits ?

**Comment by RussellGrew** [comment]
Assuming I follow, you can get a token by opening a free cesium ion account. I understand Terria have a temporary token in their repositories which expires every month or so.

You can set this as `cesiumIonAccessToken: "abc123",` in `config.json`. This last point could be better documented.

**Comment by davidedelerma** [comment]
Thanks Russel yes that works :)
Still problem with latest commits not working with Node14, but as @donnitazen said, downgrading to Node10 makes things working.

**Comment by RussellGrew** [comment]
Someone from D61 is best suited to comment on this.

I monitor https://github.com/CesiumGS/cesium/blob/master/CHANGES.md and note they mention NodeJS 12 compatibility as of April 2020 in version 1.68. In turn it is useful to keep track of Cesium versions in TerriaMap package.json to know what to expect.

Cheers.

**Comment by steve9164** [comment]
Sorry, just came across this now. At the moment TerriaMap doesn't support node 14. @RussellGrew is right about the cesiumIonAccessToken. We've just updated the Cesium version so our Ion key should be in-date again if you merge from TerriaMap `master` (and we're working on updating terriajs version 8 on the `next` branch of TerriaMap and terriajs).
