### ISSUE TITLE
TerriaJS on Windows: latest cannot install

### ISSUE THREAD

**Issue by h3rb** [TerriaJS/TerriaMap#549]
Today I for the first time tried to use TerriaJS and it got borked during build quite rapidly.

Node 14.15.4
npm 6.14.10

```text
PS E:\laragon\www\ui\TerriaMap> npm install

> husky@2.7.0 install E:\laragon\www\ui\TerriaMap\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done
husky > Like husky? You can support the project on Patreon:
husky > https://www.patreon.com/typicode 🐕

> node-sass@4.14.1 install E:\laragon\www\ui\TerriaMap\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-83_binding.node
Download complete..] - :
Binary saved to E:\laragon\www\ui\TerriaMap\node_modules\node-sass\vendor\win32-x64-83\binding.node
Caching binary to C:\Users\herb\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-83_binding.node

> core-js@2.6.12 postinstall E:\laragon\www\ui\TerriaMap\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.16.1 postinstall E:\laragon\www\ui\TerriaMap\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://paypal.me/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> terriajs-cesium@1.81.0 postinstall E:\laragon\www\ui\TerriaMap\node_modules\terriajs-cesium
> bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terriajs-cesium@1.81.0 postinstall: `bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terriajs-cesium@1.81.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\herb\AppData\Roaming\npm-cache\_logs\2021-08-18T16_00_34_357Z-debug.log
PS E:\laragon\www\ui\TerriaMap> npm run gulp

> terriajs-map@0.0.1 gulp E:\laragon\www\ui\TerriaMap
> gulp

[12:02:34] Using gulpfile E:\laragon\www\ui\TerriaMap\gulpfile.js
[12:02:34] Starting 'default'...
[12:02:34] Starting 'lint'...
[12:02:34] Error: Cannot find module 'terriajs/buildprocess/runExternalModule'
Require stack:
- E:\laragon\www\ui\TerriaMap\gulpfile.js
- E:\laragon\www\ui\TerriaMap\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js
- E:\laragon\www\ui\TerriaMap\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- E:\laragon\www\ui\TerriaMap\node_modules\gulp\node_modules\gulp-cli\index.js
- E:\laragon\www\ui\TerriaMap\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at E:\laragon\www\ui\TerriaMap\gulpfile.js:123:29
    at lint (E:\laragon\www\ui\TerriaMap\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (E:\laragon\www\ui\TerriaMap\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[12:02:34] 'default' errored after 4.16 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terriajs-map@0.0.1 gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terriajs-map@0.0.1 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\herb\AppData\Roaming\npm-cache\_logs\2021-08-18T16_02_34_996Z-debug.log
PS E:\laragon\www\ui\TerriaMap>
PS E:\laragon\www\ui\TerriaMap> npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> terriajs-cesium@1.81.0 postinstall E:\laragon\www\ui\TerriaMap\node_modules\terriajs-cesium
> bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-datepicker@0.53.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@0.53.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terriajs-cesium@1.81.0 postinstall: `bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terriajs-cesium@1.81.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\herb\AppData\Roaming\npm-cache\_logs\2021-08-18T19_23_55_430Z-debug.log
PS E:\laragon\www\ui\TerriaMap>
```

**Comment by h3rb** [comment]
Do not run it from Powershell.   Run from Git Bash.
