### ISSUE TITLE
Teria Getting Started

### ISSUE THREAD

**Issue by tiqvahub** [TerriaJS/TerriaMap#637]
Hi developers,
I'm a Teria project newcomer. First off, my apologies if  I'm writing on the wrong spot. I'm going through the getting started [guide](https://docs.terria.io/guide/getting-started/) and facing the error [1] while running **yarn install**. Would anyone point me whether or not I'm missing any configuration, please? As well, I wonder if there is any guide showing how to run TeriaMap for production using Docker.  

Server: Ubuntu Server 20.04 LTS
NodeJS: v19.5.0
npm: 9.3.1
yarn: 1.22.19

Error [1]
gyp verb get node dir target node version installed: 19.5.0
gyp verb build dir attempting to create "build" dir: /opt/teria/TerriaMap/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /opt/teria/TerriaMap/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/opt/teria/TerriaMap/node_modules/node-gyp/lib/configure.js:117:21)
gyp ERR! stack     at /opt/teria/TerriaMap/node_modules/node-gyp/lib/configure.js:84:9
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:180:23)
gyp ERR! System Linux 5.4.0-137-generic
gyp ERR! command "/usr/bin/node" "/opt/teria/TerriaMap/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/teria/TerriaMap/node_modules/node-sass
gyp ERR! node -v v19.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue

**Comment by tiqvahub** [comment]
I will close this issue.

The problem was nodejs version.
