### ISSUE TITLE
Installing dependencies with yarn install fails when packages/cesium is present

### ISSUE THREAD

**Issue by yurivyatkin** [TerriaJS/TerriaMap#702]
I am trying to enable a custom custom version of Cesium, following the documentation:
-  [Cloning and Building](https://docs-v8.terria.io/guide/customizing/cloning-and-building/).
- [Development Environment](https://docs-v8.terria.io/guide/contributing/development-environment/).
- [Using a Custom Version of Cesium](https://docs-v8.terria.io/guide/contributing/using-a-custom-version-of-cesium/).

The commands that I use:
```
export NODE_OPTIONS=--max_old_space_size=4096
git clone git@github.com:TerriaJS/TerriaMap.git
grep terriajs package.json
    "terriajs": "8.7.5",
mkdir packages
cd packages
git clone git@github.com:TerriaJS/terriajs.git
cd terriajs
git checkout 8.7.5
cd ..
git clone -b terriajs git@github.com:TerriaJS/cesium.git
cd cesium
grep version package.json
  "version": "1.92.0-tile-error-provider-fix-2",
cd ../..
yarn install
```

The versions I use are:
- Node 16.13.1
- Npm 8.1.2
- Yarn 1.19.0

In `TerriaMap/package.json` I made the following modifications:
```json
{
   "workspaces": {
    "packages": [
      "packages/terriajs",
      "packages/cesium"
    ],
    "nohoist": [
      "**/husky"
    ]
  },
  "name": "terriajs-map",
  "version": "0.2.1",
  "devDependencies": {
  // ...
    "terriajs-cesium": "1.92.0-tile-error-provider-fix-2",
  },
  // ...
}
```
In `TerriaMap/packages/terriajs/package.json`, I set the same version of `terria-cesium` as well:
```json
{
  "name": "terriajs",
  "version": "8.7.5",
// ...
  "dependencies": {
    "terriajs-cesium": "1.92.0-tile-error-provider-fix-2",
  },
// ...
}
```

Running `yarn install` fails with the following error:
```
error /Users/yuriv/Temp/TerriaMap/node_modules/terriajs-cesium: Command failed.
Exit code: 1
Command: bash -c "if [ ! -d "./wwwroot/build" ]; then gulp -f gulpfile.cjs terria-prepare-cesium; fi"
Arguments: 
Directory: /Users/yuriv/Temp/TerriaMap/node_modules/terriajs-cesium
Output:
[10:59:53] Using gulpfile ~/Temp/TerriaMap/packages/cesium/gulpfile.cjs
[10:59:53] Starting 'terria-prepare-cesium'...
[10:59:53] Starting 'prepare'...
[10:59:53] 'prepare' errored after 3.36 ms
[10:59:53] Error: Package subpath './dist/z-worker-pako.js' is not defined by "exports" in /Users/yuriv/Temp/TerriaMap/node_modules/@zip.js/zip.js/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/yuriv/Temp/TerriaMap/packages/cesium/gulpfile.cjs:390:13
    at taskWrapper (/Users/yuriv/Temp/TerriaMap/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
```

How can I get `yarn install` to work with `packages/cesium` linked?

The problem I am trying to solve by doing so is the WMS highlight issue, which has partly been solved in the mentioned version of `terrains-cesium` but not in the version `8.0.0`, which comes out of the box now.

**Comment by niktayv** [comment]
There was a lot of confusion in my first attempts, as described above.
Fortunately, Terria's team is on the way to providing more precise documentation.

In the meantime, I can just say how that works for me now.

1. Clone TerriaMap
```sh
git clone git@github.com:TerriaJS/TerriaMap.git
cd TerriaMap
mkdir packages && cd $_
git clone git@github.com:TerriaJS/terriajs.git
git clone git@github.com:TerriaJS/cesium.git
```

2. Ensure the versions and package names in `package.json` files are appropriately aligned.
 
4. Modify `TerriaMap/package.json`, the `"workspaces"` property, as follows:
```json
{
  "workspaces": {
    "packages": [
      "packages/terriajs",
      "packages/cesium/packages/engine",
      "packages/cesium/packages/widgets",
      "packages/terriajs-server",
      "packages/plugin-sample"
    ],
    "nohoist": [
      "**/husky"
    ]
  },
}
```

5. Within `TerriaMap/packages/cesium`, run
```sh
npm install
npm run release
```

6. Return (`cd ../..`) to the `TerriaMap` level, and run
```sh
yarn install
```

7. Verify that the symlinks have been created:
```sh
ls -alt node_modules | grep terriajs
```
You should see the following arrows in the last column:
```
terriajs-cesium-widgets -> ../packages/cesium/packages/widgets
terriajs-cesium -> ../packages/cesium/packages/engine
terriajs -> ../packages/terriajs
```

8. Verify that the build runs successfully
```sh
yarn gulp build
```
